/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DailyForecast {
        "data": any;
        "exclude": string;
        "iconBase": string;
        "id": string;
    }
    interface WeatherForecast {
        "apikey": string;
        "exclude": string;
        "iconBase": string;
        "lang": string;
        "lat": string;
        "lon": string;
        "units": string;
    }
}
declare global {
    interface HTMLDailyForecastElement extends Components.DailyForecast, HTMLStencilElement {
    }
    var HTMLDailyForecastElement: {
        prototype: HTMLDailyForecastElement;
        new (): HTMLDailyForecastElement;
    };
    interface HTMLWeatherForecastElement extends Components.WeatherForecast, HTMLStencilElement {
    }
    var HTMLWeatherForecastElement: {
        prototype: HTMLWeatherForecastElement;
        new (): HTMLWeatherForecastElement;
    };
    interface HTMLElementTagNameMap {
        "daily-forecast": HTMLDailyForecastElement;
        "weather-forecast": HTMLWeatherForecastElement;
    }
}
declare namespace LocalJSX {
    interface DailyForecast {
        "data"?: any;
        "exclude"?: string;
        "iconBase"?: string;
        "id"?: string;
    }
    interface WeatherForecast {
        "apikey"?: string;
        "exclude"?: string;
        "iconBase"?: string;
        "lang"?: string;
        "lat"?: string;
        "lon"?: string;
        "units"?: string;
    }
    interface IntrinsicElements {
        "daily-forecast": DailyForecast;
        "weather-forecast": WeatherForecast;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "daily-forecast": LocalJSX.DailyForecast & JSXBase.HTMLAttributes<HTMLDailyForecastElement>;
            "weather-forecast": LocalJSX.WeatherForecast & JSXBase.HTMLAttributes<HTMLWeatherForecastElement>;
        }
    }
}
